site_name: note
site_url: https://cybotiger.github.io/note/
site_author: cybotiger

repo_url: https://github.com/cyboTiger/note
repo_name: cyboTiger/note


theme:
  name: material
  features:
    - navigation.tracking  # 锚点跟踪
    - navigation.tabs # 顶部导航
    - navigation.sections # 按 section 展开侧栏
    - navigation.indexes # index 页面不显示在侧栏
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: zh
  font:
    text: Roboto
    code: JetBrains Mono
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: lime
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: lime
  favicon: assets/img/kagula.svg
  logo: assets/img/kagula.svg

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - attr_list
  - def_list
  - md_in_html
  - sane_lists
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.blocks.caption # figure caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:  #任务列表
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home:
    - index.md
  - 数学:
    - math/index.md
    - 反向传播: math/backprop.md
  - 深度学习:
    - dl/index.md
    - Attention:
      - Flash Attention: dl/attention/flash_attn.md
      - Flex Attention: dl/attention/flex_attn.md
    - 神经网络架构:
      - CNN: dl/nn/cnn.md
    - 推理:
      - SGLang: dl/inference/sglang.md
    - 训练:
      - 优化器: dl/training/optim.md
      - fsdp: dl/training/fsdp.md
  - MLSys:
    - torch distributed: sys/torch_distributed.md
    - 编译器:
      - 编程语言:
        - Rust: sys/pl/lang/rust.md
        - Python: sys/pl/lang/python.md
        - Cuda: sys/pl/lang/cuda.md
        - PyTorch: sys/pl/lang/pytorch.md
        - Triton-lang: sys/pl/lang/triton.md
      - 编译工具链:
        - CMake: sys/pl/compile/cmake.md
        - Make: sys/pl/compile/make.md
        - C Compiler: sys/pl/compile/ccompiler.md
        - GDB: sys/pl/compile/gdb.md
  - 具身智能:
    - robotics/index.md
  - 其他:
    - other/index.md
    - 工具:
      - other/tool/docker.md
      - other/tool/linux_cmd.md
      - other/tool/python_pkg.md
      - other/tool/vim.md
      - other/tool/cicd.md
      - other/tool/vscode.md


extra_javascript:
  - assets/js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # for katex 

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # for katex
  - stylesheets/extra.css

# strict: false
# use_directory_urls: true  # 保持默认即可